### ISSUE TITLE
Add a way not to show a program in TOC?

### ISSUE THREAD

**Issue by mmagnus** [sphinx-contrib/autoprogram#52] opened 2022-08-26 10:16 UTC
Is there a way not to add a program to TOC?
https://rna-tools.readthedocs.io/en/latest/
![sc 2022-08-26 at 12 16 13](https://user-images.githubusercontent.com/118740/186882634-5cccb7f3-d0da-4f4a-bcdc-1ec0594d856f.jpg)

**Comment by langston-barrett** [comment] 2022-08-30 13:39
Duplicate of #22. PRs welcome!

**Closed by langston-barrett** 2022-08-30 13:39 UTC

**Comment by mmagnus** [comment] 2022-09-06 09:44
Aaa, ok, sorry for that. Thanks for pointing this out @langston-barrett
